import { Component } from '@angular/core';
import { ServiceItem } from '../service-item.interface';
import { ServicesListService } from '../services.service';
import { Order } from '../order';
import { CookieService } from 'ngx-cookie-service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { InvoiceService } from '../invoice.service';


@Component({
  selector: 'app-service',
  templateUrl: './service.component.html',
  styleUrls: ['./service.component.css']
})
export class ServiceComponent {
// Create array of services from ServiceItem Interface
  services: Array<ServiceItem>;
  user: any;
  // Set up Order content from Order Class
  order: Order;

  email: string = ''
  fullName: string = ''

  isLoading: boolean = false;
  errorMessage: string;
  // Set form submitted to false until user selects the submit button
  formSubmitted: boolean = false;

  // Set up form validation
  serviceRequestForm: FormGroup = this.fb.group({
    email: [null, Validators.compose([Validators.required, Validators.email])],
    fullName: [null, Validators.compose([Validators.required])]
  })

  constructor(
    private serviceListService: ServicesListService,
    private router: Router,
    private cookieService: CookieService,
    private route: ActivatedRoute,
    private fb: FormBuilder,
    private invoiceService: InvoiceService
  ) {
    // Create a new instance of Order object
    this.order = new Order();
    // Set Id to be generated by random number.
    this.order.id = Math.floor(Math.random() * 10000) + 10000;
    // set order's date to day user creates service request
    this.order.date = new Date().toLocaleDateString();

    // call getServiceList() to get an array of services
    this.services = this.serviceListService.getServiceList();

    this.errorMessage = '';

    // Get session_user
    const session_user =  this.cookieService.get('session_user')
    if (session_user) {
      this.user = JSON.parse(session_user)
    }


  }

  // Create a new service request
  createOrder () {
    // When user clicks the submit button, formSubmitted is true.
    this.formSubmitted = true;

    // Search the array of services where checked property is true
    // For each checked service, grab the name and price and push it to the lineItems array of the order.
    for (let item of this.services) {
      if (item.checked) {
        const {name, price} = item;
        this.order.lineItems.push({name, price} as any)
      }
    }
    // Call the servicesTotal() function from the Order Class to calculate the total cost for  lineItems.
    this.order.servicesTotal();

    // Set partsAmount
    this.order.partsAmount = parseFloat(this.order.partsAmount.toString());
    // set laborAmount
    this.order.laborAmount =  parseFloat((this.order.laborAmount * 50).toString());

    console.log(this.order.partsAmount);
    console.log (this.order.laborAmount);
    // Call the getOrderTotal to calculate the total cost of services, parts, and labor.
    this.order.invoiceTotal = parseFloat(this.order.getOrderTotal());

     console.log("invoiceTotal:", this.order.invoiceTotal)
     // Set order form created to variable formData
     let formData = this.order;

     // Call createInvoice API from invoiceService

     this.invoiceService.createInvoice(formData). subscribe({
      next: (res) => {
        this.isLoading = false;
        // Route to the invoice summary page
        this.router.navigate(['invoice-summary'])
      },
       error: (err) => {
        if (err.errorMessage.message) {
          this.errorMessage = err.error.message
          this.isLoading = false;
        } else {
          this.errorMessage= 'Something went wrong';
          this.isLoading = false
        }
      }
     })


  }




}
